[package]
name = "thirty-thirty"
version = "0.1.0"
edition = "2024"
authors = ["Adam Chalmers", "Zoo Corporation (zoo.dev)"]
description = "3D diffing algorithm"

[workspace.lints.clippy]
assertions_on_result_states = "warn"
dbg_macro = "warn"
iter_over_hash_type = "warn"
lossy_float_literal = "warn"
redundant_clone = "warn"
result_large_err = "allow"

[workspace.lints.rust]
unsafe_code = "deny"

[dependencies]
camino = "1.2.6"
log = "0.4.34"
mesh_to_sdf = "0.4.0"
parry3d = "0.28"
rs-read-trimesh = "2.0.10"
thiserror = "2.0.21"


[patch.crates-io]
rs-read-trimesh = { git = "https://github.com/adamchalmers/rs-read-trimesh", branch = "achalmers/gltf" }
